sudo:
  false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
before_script:
  - composer install --dev --no-interaction
script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist
notifications:
  email:
    maccotsan@gmail.com
